import type { WorkflowNode, WorkflowEdge } from "@/components/workflow/types";

export interface WorkflowTemplate {
  name: string;
  description: string;
  nodes: WorkflowNode[];
  edges: WorkflowEdge[];
}

export const parfymBannerTemplate: WorkflowTemplate = {
  name: "Parfym Banner Campaign",
  description: "Generate SE/NO/EN parfym banners in 3 formats using AI",
  nodes: [
    // Column 1 — inputs
    {
      id: "tpl-file",
      type: "file",
      position: { x: 50, y: 50 },
      data: { label: "Product Photo", fileType: undefined } as WorkflowNode["data"],
    },
    {
      id: "tpl-product",
      type: "productInput",
      position: { x: 50, y: 350 },
      data: {
        label: "Product Input",
        prompt: "",
        productName: "",
        brand: "",
        scentNotes: "",
        styleKeywords: "",
        brandColor: "",
        taglineDirection: "",
      } as WorkflowNode["data"],
    },

    // Column 2 — language prompts
    {
      id: "tpl-lp-se",
      type: "languagePrompt",
      position: { x: 450, y: 50 },
      data: {
        label: "Language Prompt",
        language: "sv",
        contentType: "hero",
        prompt: "",
        isGenerating: false,
      } as WorkflowNode["data"],
    },
    {
      id: "tpl-lp-no",
      type: "languagePrompt",
      position: { x: 450, y: 350 },
      data: {
        label: "Language Prompt",
        language: "no",
        contentType: "hero",
        prompt: "",
        isGenerating: false,
      } as WorkflowNode["data"],
    },
    {
      id: "tpl-lp-en",
      type: "languagePrompt",
      position: { x: 450, y: 650 },
      data: {
        label: "Language Prompt",
        language: "en",
        contentType: "hero",
        prompt: "",
        isGenerating: false,
      } as WorkflowNode["data"],
    },

    // Column 3 — Hero 16:9 images
    {
      id: "tpl-nbp-se-hero",
      type: "nanoBananaPro",
      position: { x: 850, y: 50 },
      data: {
        label: "Nano Banana Pro",
        prompt: "",
        mode: "text-to-image",
        aspectRatio: "16:9",
        resolution: "2K",
        outputFormat: "webp",
        numImages: 1,
        enableWebSearch: false,
        enableSafetyChecker: true,
        inputCount: 5,
      } as WorkflowNode["data"],
    },
    {
      id: "tpl-nbp-no-hero",
      type: "nanoBananaPro",
      position: { x: 850, y: 350 },
      data: {
        label: "Nano Banana Pro",
        prompt: "",
        mode: "text-to-image",
        aspectRatio: "16:9",
        resolution: "2K",
        outputFormat: "webp",
        numImages: 1,
        enableWebSearch: false,
        enableSafetyChecker: true,
        inputCount: 5,
      } as WorkflowNode["data"],
    },
    {
      id: "tpl-nbp-en-hero",
      type: "nanoBananaPro",
      position: { x: 850, y: 650 },
      data: {
        label: "Nano Banana Pro",
        prompt: "",
        mode: "text-to-image",
        aspectRatio: "16:9",
        resolution: "2K",
        outputFormat: "webp",
        numImages: 1,
        enableWebSearch: false,
        enableSafetyChecker: true,
        inputCount: 5,
      } as WorkflowNode["data"],
    },

    // Column 4 — Square 1:1 images
    {
      id: "tpl-nbp-se-sq",
      type: "nanoBananaPro",
      position: { x: 1250, y: 50 },
      data: {
        label: "Nano Banana Pro",
        prompt: "",
        mode: "text-to-image",
        aspectRatio: "1:1",
        resolution: "2K",
        outputFormat: "webp",
        numImages: 1,
        enableWebSearch: false,
        enableSafetyChecker: true,
        inputCount: 5,
      } as WorkflowNode["data"],
    },
    {
      id: "tpl-nbp-no-sq",
      type: "nanoBananaPro",
      position: { x: 1250, y: 350 },
      data: {
        label: "Nano Banana Pro",
        prompt: "",
        mode: "text-to-image",
        aspectRatio: "1:1",
        resolution: "2K",
        outputFormat: "webp",
        numImages: 1,
        enableWebSearch: false,
        enableSafetyChecker: true,
        inputCount: 5,
      } as WorkflowNode["data"],
    },
    {
      id: "tpl-nbp-en-sq",
      type: "nanoBananaPro",
      position: { x: 1250, y: 650 },
      data: {
        label: "Nano Banana Pro",
        prompt: "",
        mode: "text-to-image",
        aspectRatio: "1:1",
        resolution: "2K",
        outputFormat: "webp",
        numImages: 1,
        enableWebSearch: false,
        enableSafetyChecker: true,
        inputCount: 5,
      } as WorkflowNode["data"],
    },

    // Column 5 — Story 9:16 images
    {
      id: "tpl-nbp-se-st",
      type: "nanoBananaPro",
      position: { x: 1650, y: 50 },
      data: {
        label: "Nano Banana Pro",
        prompt: "",
        mode: "text-to-image",
        aspectRatio: "9:16",
        resolution: "2K",
        outputFormat: "webp",
        numImages: 1,
        enableWebSearch: false,
        enableSafetyChecker: true,
        inputCount: 5,
      } as WorkflowNode["data"],
    },
    {
      id: "tpl-nbp-no-st",
      type: "nanoBananaPro",
      position: { x: 1650, y: 350 },
      data: {
        label: "Nano Banana Pro",
        prompt: "",
        mode: "text-to-image",
        aspectRatio: "9:16",
        resolution: "2K",
        outputFormat: "webp",
        numImages: 1,
        enableWebSearch: false,
        enableSafetyChecker: true,
        inputCount: 5,
      } as WorkflowNode["data"],
    },
    {
      id: "tpl-nbp-en-st",
      type: "nanoBananaPro",
      position: { x: 1650, y: 650 },
      data: {
        label: "Nano Banana Pro",
        prompt: "",
        mode: "text-to-image",
        aspectRatio: "9:16",
        resolution: "2K",
        outputFormat: "webp",
        numImages: 1,
        enableWebSearch: false,
        enableSafetyChecker: true,
        inputCount: 5,
      } as WorkflowNode["data"],
    },
  ],

  edges: [
    // ProductInput → LanguagePrompt (3 edges)
    {
      id: "e-product-lp-se",
      source: "tpl-product",
      sourceHandle: "prompt",
      target: "tpl-lp-se",
      targetHandle: "prompt",
      type: "gradient",
    },
    {
      id: "e-product-lp-no",
      source: "tpl-product",
      sourceHandle: "prompt",
      target: "tpl-lp-no",
      targetHandle: "prompt",
      type: "gradient",
    },
    {
      id: "e-product-lp-en",
      source: "tpl-product",
      sourceHandle: "prompt",
      target: "tpl-lp-en",
      targetHandle: "prompt",
      type: "gradient",
    },

    // LanguagePrompt → NanoBananaPro (9 edges)
    {
      id: "e-lp-se-nbp-se-hero",
      source: "tpl-lp-se",
      sourceHandle: "prompt",
      target: "tpl-nbp-se-hero",
      targetHandle: undefined,
      type: "gradient",
    },
    {
      id: "e-lp-se-nbp-se-sq",
      source: "tpl-lp-se",
      sourceHandle: "prompt",
      target: "tpl-nbp-se-sq",
      targetHandle: undefined,
      type: "gradient",
    },
    {
      id: "e-lp-se-nbp-se-st",
      source: "tpl-lp-se",
      sourceHandle: "prompt",
      target: "tpl-nbp-se-st",
      targetHandle: undefined,
      type: "gradient",
    },
    {
      id: "e-lp-no-nbp-no-hero",
      source: "tpl-lp-no",
      sourceHandle: "prompt",
      target: "tpl-nbp-no-hero",
      targetHandle: undefined,
      type: "gradient",
    },
    {
      id: "e-lp-no-nbp-no-sq",
      source: "tpl-lp-no",
      sourceHandle: "prompt",
      target: "tpl-nbp-no-sq",
      targetHandle: undefined,
      type: "gradient",
    },
    {
      id: "e-lp-no-nbp-no-st",
      source: "tpl-lp-no",
      sourceHandle: "prompt",
      target: "tpl-nbp-no-st",
      targetHandle: undefined,
      type: "gradient",
    },
    {
      id: "e-lp-en-nbp-en-hero",
      source: "tpl-lp-en",
      sourceHandle: "prompt",
      target: "tpl-nbp-en-hero",
      targetHandle: undefined,
      type: "gradient",
    },
    {
      id: "e-lp-en-nbp-en-sq",
      source: "tpl-lp-en",
      sourceHandle: "prompt",
      target: "tpl-nbp-en-sq",
      targetHandle: undefined,
      type: "gradient",
    },
    {
      id: "e-lp-en-nbp-en-st",
      source: "tpl-lp-en",
      sourceHandle: "prompt",
      target: "tpl-nbp-en-st",
      targetHandle: undefined,
      type: "gradient",
    },

    // FileNode → NanoBananaPro (9 edges — image to image1)
    {
      id: "e-file-nbp-se-hero",
      source: "tpl-file",
      sourceHandle: "image",
      target: "tpl-nbp-se-hero",
      targetHandle: "image1",
      type: "gradient",
    },
    {
      id: "e-file-nbp-se-sq",
      source: "tpl-file",
      sourceHandle: "image",
      target: "tpl-nbp-se-sq",
      targetHandle: "image1",
      type: "gradient",
    },
    {
      id: "e-file-nbp-se-st",
      source: "tpl-file",
      sourceHandle: "image",
      target: "tpl-nbp-se-st",
      targetHandle: "image1",
      type: "gradient",
    },
    {
      id: "e-file-nbp-no-hero",
      source: "tpl-file",
      sourceHandle: "image",
      target: "tpl-nbp-no-hero",
      targetHandle: "image1",
      type: "gradient",
    },
    {
      id: "e-file-nbp-no-sq",
      source: "tpl-file",
      sourceHandle: "image",
      target: "tpl-nbp-no-sq",
      targetHandle: "image1",
      type: "gradient",
    },
    {
      id: "e-file-nbp-no-st",
      source: "tpl-file",
      sourceHandle: "image",
      target: "tpl-nbp-no-st",
      targetHandle: "image1",
      type: "gradient",
    },
    {
      id: "e-file-nbp-en-hero",
      source: "tpl-file",
      sourceHandle: "image",
      target: "tpl-nbp-en-hero",
      targetHandle: "image1",
      type: "gradient",
    },
    {
      id: "e-file-nbp-en-sq",
      source: "tpl-file",
      sourceHandle: "image",
      target: "tpl-nbp-en-sq",
      targetHandle: "image1",
      type: "gradient",
    },
    {
      id: "e-file-nbp-en-st",
      source: "tpl-file",
      sourceHandle: "image",
      target: "tpl-nbp-en-st",
      targetHandle: "image1",
      type: "gradient",
    },
  ],
};
